### ISSUE TITLE
document config.yaml options

### ISSUE THREAD

**Issue by hbjydev** [hbjydev/zet#1]
```yaml
---
root: '<root of the zettelkasten>'
repo: '<remote repo url of the zettelkasten to sync with>'
```
